class UrlDataModel {
  List<AdressModel> address;
  UrlDataModel({required this.address});

  factory UrlDataModel.fromJson(Map<String, dynamic> json) {
    try {
      return UrlDataModel(
        address:
            (json["data"] as List).map((e) => AdressModel.fromJson(e)).toList(),
      );
    } catch (e) {
      return UrlDataModel(
        address: [],
      );
    }
  }
}

class AdressModel {
  late final int? adressId; //beacause rightnow id is autogenerated by local db
  late final String adressTitle;
  late final double lat;
  late final double long;
  late final String?
      country; // it is only use when we call api and then we filter the address of pakistan

  AdressModel(
      {this.adressId,
      required this.adressTitle,
      required this.lat,
      required this.long,
      this.country});

  String get getId => adressId.toString();
  String get getAdressTitle => adressTitle;

  static AdressModel fromDictionary(Map<String, Object?> json) => AdressModel(
        adressId: json[AdressFields.id] as int?,
        adressTitle: json[AdressFields.adressTitle] as String,
        long: json[AdressFields.longitude] as double,
        lat: json[AdressFields.latitude] as double,
        country: json['country'] as String?,
      );

  // static AdressModel fromJson(Map<String, dynamic> json) => AdressModel(
  //       adressId: json[AdressFields.id] as int?,
  //       adressTitle: json["properties"]["name"] as String,
  //       long: json["properties"]["lon"] as double,
  //       lat: json["properties"]["lat"] as double,
  //       country: json["properties"]['country'] as String?,
  //     );

  static AdressModel fromJson(Map<String, dynamic> json) => AdressModel(
      adressId: json[AdressFields.id] as int?,
      adressTitle: json[AdressFields.adressTitle],
      country: json["country"],
      lat: json[AdressFields.latitude],
      long: json[AdressFields.longitude]);

  Map<String, Object?> toDictonary() => {
        AdressFields.id: adressId,
        AdressFields.adressTitle: adressTitle,
        AdressFields.latitude: lat,
        AdressFields.longitude: long
      };

  AdressModel copy({int? id, String? title, double? lat, double? long}) =>
      AdressModel(
          adressId: id ?? this.adressId,
          adressTitle: title ?? this.adressTitle,
          lat: lat ?? this.lat,
          long: long ?? this.long);
//
// CommentSample({this.postId, this.id, this.name, this.email, this.body});
//
// CommentSample.fromJson(Map<String, dynamic> json) {
//   postId = json['postId'];
//   id = json['id'];
//   name = json['name'];
//   email = json['email'];
//   body = json['body'];
// }
//
// Map<String, dynamic> toJson() {
//   final Map<String, dynamic> data = new Map<String, dynamic>();
//   data['postId'] = this.postId;
//   data['id'] = this.id;
//   data['name'] = this.name;
//   data['email'] = this.email;
//   data['body'] = this.body;
//   return data;
// }
}

class AdressFields {
  static final List<String> values = [id, adressTitle, longitude, latitude];

  static final String id = 'id';
  static final String adressTitle = 'label';
  static final String longitude = 'longitude';
  static final String latitude = 'latitude';
}
